require("config.lazy")
require("config.editor")
require("config.remap")
require("config.telescope")
require("config.tokyonight")
require("config.gitsigns")
require("config.lsp")
require("config.term")
